BlogApplication/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using BlogApplication;
using BlogApplication.Autofac;
using ImageResizer;
using PagedList;

namespace BlogApplication.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PostsController : Controller
    {
        private readonly IService<Post> _postService;
        private readonly IService<Category> _categoryService;

        public PostsController(IService<Post> postService, IService<Category> categoryService)
        {
            _postService = postService;
            _categoryService = categoryService;
        }

        // GET: Posts
        public ActionResult Index(int page = 1)
        {
            return View(_postService.ListAll().ToPagedList(page, 10));
        }

        public ActionResult Details(Guid id)
        {
            return View(_postService.FindById(id));
        }

        // GET: Posts/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(_categoryService.SelectListValues(), "Id", "Name");
            return View();
        }

        // POST: Posts/Create        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryId,Title,Description,Content")] Post post, HttpPostedFileBase file)
        {            
            if (file == null || file.ContentLength <= 0)
            {
                ModelState.AddModelError("File", "Image file is required");
            }

            if (string.IsNullOrEmpty(post.Title))
            {
                ModelState.AddModelError("Title", "Title is required");                
            }

            if (string.IsNullOrEmpty(post.Description))
            {
                ModelState.AddModelError("Description", "Description is required");
            }

            if (string.IsNullOrEmpty(post.Content))
            {
                ModelState.AddModelError("Content", "Content is required");
            }            

            if (ModelState.IsValid && file != null && file.ContentLength > 0)
            {
                Post.AddPostPhotos(file, post);                                   
                _postService.Add(post);
                return RedirectToAction("Index");
            }
            
            ViewBag.CategoryId = new SelectList(_categoryService.SelectListValues(), "Id", "Name");
            return View(post);
        }

        // GET: Posts/Edit/id
        public ActionResult Edit(Guid id)
        {            
            var post = _postService.FindById(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(_categoryService.SelectListValues(), "Id", "Name", post.CategoryId);
            return View(post);
        }

        // POST: Posts/Edit/id 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Post post, HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                Post.AddPostPhotos(file, post);
            }

            if (string.IsNullOrEmpty(post.Title))
            {
                ModelState.AddModelError("Title", "Title is required");
            }

            if (string.IsNullOrEmpty(post.Description))
            {
                ModelState.AddModelError("Description", "Description is required");
            }

            if (string.IsNullOrEmpty(post.Content))
            {
                ModelState.AddModelError("Content", "Content is required");
            }   

            if (ModelState.IsValid)
            {
                _postService.Update(post);
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(_categoryService.SelectListValues(), "Id", "Name", post.CategoryId);
            return View(post);
        }

        // GET: Posts/Delete/id
        public ActionResult Delete(Guid id)
        {            
            var post = _postService.FindById(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Posts/Delete/id
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            var post = _postService.FindById(id);
            Post.RemoveImageFile(Server.MapPath(post.ThumbnailPath), Server.MapPath(post.ImagePath));
            _postService.Delete(id);            
            return RedirectToAction("Index");
        }               
    }
}

BlogApplication/Views/Posts/Create.cshtml
@model BlogApplication.Post

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Posts", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary("", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control"}})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Content, new {htmlAttributes = new {@class = "form-control"}})
                <p>Powered by &copy; <a href="http://ckeditor.com/">CKEditor</a></p>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Cover image</label>
            <div class="col-md-10">
                <input type="file" accept=".jpg,.png" name="file" id="file"/>                
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script> CKEDITOR.replace('Content'); </script>
}

BlogApplication/Views/Posts/Delete.cshtml
@model BlogApplication.Post

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this? This will also delete all of the related COMMENTS</h3>
<div>    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>        

        <dt>
            Category
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.Raw(Model.Content)
        </dd>       
    </dl>    
</div>

BlogApplication/Views/Posts/Details.cshtml
@model BlogApplication.Post

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Post</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>        

        <dt>
            Category
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThumbnailPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThumbnailPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.Raw(Model.Content)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BlogApplication/Views/Posts/Edit.cshtml
@model BlogApplication.Post

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Posts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary("", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.ThumbnailPath)
        @Html.HiddenFor(model => model.ImagePath)
        @Html.HiddenFor(model => model.Created)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control"}})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Content, new {htmlAttributes = new {@class = "form-control"}})                
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Cover image</label>
            <div class="col-md-10">
                <input type="file" accept=".jpg,.png" name="file" id="file" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script> CKEDITOR.replace('Content'); </script>
}

BlogApplication/Views/Posts/Index.cshtml
@model PagedList.IPagedList<Post>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered table-striped">
    <tr>
        <th>
            Title
        </th>        
        <th>
            Category Name
        </th>
        <th>Date created</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>            
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Comments", "Index", "Comments", new { id = item.Id }, null) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }),
    PagedListRenderOptions.Classic)